### ISSUE TITLE
Furni data

### ISSUE THREAD

**Issue by DavydeVries** [gerbenjacobs/HabboAPI#10]
### Furni data

Maybe add furni data to the API?
I have some ideas for that and like to program that ;)

**Comment by gerbenjacobs** [comment]
So I found it for nl, com and sandbox. But for example there is nothing for de.
I'm not sure if we should have this, or only use com. What are your ideas for this?

**Comment by DavydeVries** [comment]
`habbo.'.$hotel.'/gamedata/furnidata/1`
would be do the trick I guess

**Comment by gerbenjacobs** [comment]
Ahh I see. If you want you can work on this, I have created a branch called `v2` and started working on `v2-photos` that adds a new Photo entity and also changed the HabboParser to have more methods. You could do something similarly.

**Comment by DavydeVries** [comment]
#26

**Comment by gerbenjacobs** [comment]
Although the endpoint is interesting, I don't think it fits with the HabboAPI and as such I'm closing this issue.
