### ISSUE TITLE
PHP version support

### ISSUE THREAD

**Issue by gerbenjacobs** [gerbenjacobs/HabboAPI#13]
So for v2 I kinda wanted to drop 5.3, however, I just found this: http://w3techs.com/technologies/details/pl-php/5/all

I'm not sure how up to date this is and how big their target audience is, so really it would be nice to get some facts from current Habbo fansites on what version of PHP they use (I think 90% uses PHP).

**Comment by DavydeVries** [comment]
> (I think 90% uses PHP)

I have never seen a Habbo fansite that use something else than PHP. 
But I use, PHP version 5.5.29

I love the short array syntax (PHP version 5.4.0 and above). It's shorter like five characters per array XD.
But I have no problems to drop or support PHP version 5.3. It's not a big problem.

**Comment by gerbenjacobs** [comment]
I will leave this issue open for another day, after which I'll up the version to 5.4 minimum and start introducing 5.6 in the Travis config.

Even though these statistics say dropping 5.3 isn't that great; http://w3techs.com/technologies/details/pl-php/5/all
