### ISSUE TITLE
Add Carbon support for all datetime values

### ISSUE THREAD

**Issue by gerbenjacobs** [gerbenjacobs/HabboAPI#16]
Now that we are about to add Photos to the API, which uses a timestamp for their data and we have several other formats floating around the HabboAPI, perhaps we should use Carbon (https://github.com/briannesbitt/Carbon) to create, in essence, Time entities.

**Comment by DavydeVries** [comment]
Do it! It's so much better if the user/developer can make a decision about time/date format.
