### ISSUE TITLE
Create Profile entity

### ISSUE THREAD

**Issue by gerbenjacobs** [gerbenjacobs/HabboAPI#2]
Will force the expected output on the getProfile() method instead of relying on some kind of array.

**Comment by DavydeVries** [comment]
So the old array with `['habbo','friends','badges','rooms','groups']` will be removed? And will be replaced with a object in the object profile?

**Comment by gerbenjacobs** [comment]
Yep, see https://github.com/gerbenjacobs/HabboAPI/commit/f538af60f07559ad0e32595024275fd7c2eb0ef7#diff-8c1510ea2991d95030094ed1dc016272R84
