### ISSUE TITLE
Sometimes there is no officialRoom attribute

### ISSUE THREAD

**Issue by gerbenjacobs** [gerbenjacobs/HabboAPI#21]
See: 
- https://www.habbo.fi/api/public/users/hhfi-2f93fc04da74913ac74f861e948d1543/profile
- https://www.habbo.fi/api/public/users/hhus-62fb4de117d96b297e5155535b025e1f/profile

They (or this Habbo) appear to not have the `officialRoom: true` attribute.

(The HHUS example even has a completely different attribute of `showOwnerName: true`

**Comment by DavydeVries** [comment]
I checked the `us` profile and `fi` profile. I can't find `officialRoom` on both profiles. Maybe this is experimental by Habbo? They have changed the room api several times in the past 2 weeks.
