### ISSUE TITLE
Online Counter & Habbo-Build

### ISSUE THREAD

**Issue by chris-redbeed** [gerbenjacobs/HabboAPI#29]
Hey,

any one knows how to get the count of online Habbos, and the last Build of Habbo?

Thanks,
Chris

**Comment by DavydeVries** [comment]
I'm not sure, but I believe that this information has been removed.

Possible reason: the low online Habbos numbers.

**Comment by chris-redbeed** [comment]
But You can find a online counter and build on https://stats.bubblejuice.nl/home

**Comment by gerbenjacobs** [comment]
They're not on the new Habbo Web. But only on the old websites.

**Comment by chris-redbeed** [comment]
Oh.. You can visit the old Pages?

**Comment by gerbenjacobs** [comment]
Yep, but I'm not sure how long Sulake will keep these up.

For example you can go here https://habbohotel.at/ (accept the HTTPS warning and don't put www)

**Comment by chris-redbeed** [comment]
Oh okay.. It works for all hotel?
https://twitter.com/bubblejuicenl/status/679615908105588737

**Comment by DavydeVries** [comment]
> For example you can go here https://habbohotel.at/ (accept the HTTPS warning and don't put www)

habbohotel.nl is in maintenance. But probably this is in maintenance since the new web version.

> Oh okay.. It works for all hotel?
> https://twitter.com/bubblejuicenl/status/679615908105588737

Yes, probably this will work for all hotels. But why you want this information?

**Comment by DavydeVries** [comment]
> Oh okay.. It works for all hotel?
https://twitter.com/bubblejuicenl/status/679615908105588737

Yes, probably this will work for all hotels. But why you want this information?

**Comment by chris-redbeed** [comment]
To display this on HabboAura :-)
