### ISSUE TITLE
HabboParser('de')?

### ISSUE THREAD

**Issue by ghost** [gerbenjacobs/HabboAPI#39]
Hey! When I edit the HabboParser to the German Habbo, I have a blank website?

Code:
`$habboParser = new HabboParser('de');`

The Habboname exists.. Can anyone help?

**Comment by ghost** [comment]
The error:

> Fatal error: Uncaught HabboAPI\Exceptions\HabboNotFoundException: [0]: We can not find the Habbo you're looking for thrown in /var/www/vhosts/file/httpdocs/vendor/gerbenjacobs/habbo-api/src/HabboParser.php on line 236

But the Habbo exists in the German Hotel?

**Comment by gerbenjacobs** [comment]
It could mean they don't exist, they are banned or the hotel was temporarily down.
If it still occurs, can you send me the name, then I'll have a look if I can debug it

**Comment by ghost** [comment]
I have tested many names.

For example:
mathys or ursli6

**Comment by gerbenjacobs** [comment]
I've tried with this 
```
<?php
    // Include the Composer autoloader
    include 'vendor/autoload.php';

    // Shortcut for the FQN
    use HabboAPI\HabboAPI;
    use HabboAPI\HabboParser;

    // Create new Parser and API instance
    $habboParser = new HabboParser('de');
    $habboApi = new HabboAPI($habboParser);

   
    $habbo = $habboApi->getHabbo('ursli6');
    $profile = $habboApi->getProfile($habbo->getId());
    
    print_r($habbo);
    print_r($profile);
```

And it works:

```
$ php index.php
HabboAPI\Entities\Habbo Object
(
    [id:HabboAPI\Entities\Habbo:private] => hhde-da746ccef5f4b32b4c1f3ae4ab38e09
1
    [habboName:HabboAPI\Entities\Habbo:private] => ursli6
    [motto:HabboAPI\Entities\Habbo:private] =>       Holla the Forest-Fairy!
    [memberSince:HabboAPI\Entities\Habbo:private] => Carbon\Carbon Object
        (
            [date] => 2005-07-12 14:04:46.000000
            [timezone_type] => 1
            [timezone] => +00:00
        )

    [figureString:HabboAPI\Entities\Habbo:private] => hr-540-44.hd-600-1370.ch-3
528-64-1408.lg-3391-81-1408.he-3274-1408.ea-3484
    [profileVisible:HabboAPI\Entities\Habbo:private] => 1

... <snip> ...
```

With a composer.json that looks like this

```
{
    "require": {
        "gerbenjacobs/habbo-api": "^2.2"
    }
}
```


It could be that the hotel was down. I'm just noticing that I moved the MaintenanceException to the top of the function but never released that as a new packagist update.
