### ISSUE TITLE
Custom message - throw new Exception (HabboParser.php)(dutch)

### ISSUE THREAD

**Issue by DavydeVries** [gerbenjacobs/HabboAPI#4]
Misschien de `error code` en `error status` terug geven in `HabboParser.php`?
In plaats van de zin `Habbo API replied with an error code:`
###### Reden:

Zo kan iemand makkelijk op basis van `error code` of `error status` een eigen custom error melding maken. Zoals:
- `400`: `Bad Request`
- `404`: `Habbo niet gevonden.`
###### Oud:

```
if ($data['habboAPI_info']['http_code'] != 200)
{
throw new Exception('Habbo API replied with an error code: ' . $data['error']);
}
```
##### Suggestie:

```
if ($data['habboAPI_info']['http_code'] != 200)
{
throw new Exception($data['error'], $data['habboAPI_info']['http_code']);
}
```

Of als je een beter idee hebt dat dit, zoals een message bag of iets dergelijks mag natuurlijk ook ;)

**Comment by gerbenjacobs** [comment]
Fixed in #6
