### ISSUE TITLE
FigureString Gender

### ISSUE THREAD

**Issue by Pandafuchs** [gerbenjacobs/HabboAPI#42]
This is not an issue with the HabboAPI PHP Wrapper, but this place just seems to be full of intelligent people so I might just ask here:

Are you able to extract the gender from a FigureString?

**Comment by gerbenjacobs** [comment]
Nope, the figurestring knows no gender, some items are just gender specific.

It would be possible through deduction if we have something like #36 working. It would look at the hair, shirt and trousers/skirt and make a guess if these are the typical M or F clothes.

**Comment by Pandafuchs** [comment]
Oh that's a good idea but not very reliable. I really thought it contained the gender though :/
