### ISSUE TITLE
Members of a group

### ISSUE THREAD

**Issue by francoisleduc** [gerbenjacobs/HabboAPI#45]
https://github.com/gerbenjacobs/HabboAPI/blob/f7d81d50194ff0618dfeb3b72db9a8b90f6613b3/src/HabboParser.php#L169

I'm not sure Habbo gives the possibility to extract members of a group in their API. Where have you found this ?

**Comment by gerbenjacobs** [comment]
True. This used to work for some (smaller) groups, but recently they've completely disabled it.
Removing it from the code requires a major version update according to semver, so I'll leave it in for now.
