### ISSUE TITLE
Update Carbon and/or allow newer versions

### ISSUE THREAD

**Issue by gerbenjacobs** [gerbenjacobs/HabboAPI#47]
At the moment HabboAPI uses Carbon 1.2 but the latest version is 2.6. We need to investigate whether we can add 2.6 as is, or if we have breaking changes. If so, update Carbon to 2.6

**Comment by TylerLumen** [comment]
I become this error when I will install the package:

`Using version ^3.0 for gerbenjacobs/habbo-api
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install gerbenjacobs/habbo-api v3.0.1
    - Conclusion: remove nesbot/carbon 2.31.0
    - Installation request for gerbenjacobs/habbo-api ^3.0 -> satisfiable by gerbenjacobs/habbo-api[v3.0.0, v3.0.1].
    - Conclusion: don't install nesbot/carbon 2.31.0
    - gerbenjacobs/habbo-api v3.0.0 requires nesbot/carbon ^1.29 -> satisfiable by nesbot/carbon[1.29.0, 1.29.1, 1.29.2, 1.30.0, 1.31.0, 1.31.1, 1.32.0, 1.33.0, 1.34.0, 1.34.1, 1.34.2, 1.34.3, 1.34.4, 1.35.0, 1.35.1, 1.36.0, 1.36.1, 1.36.2, 1.37.0, 1.37.1, 1.38.0, 1.38.1, 1.38.2, 1.38.3, 1.38.4, 1.39.0, 1.39.1].
    - Can only install one of: nesbot/carbon[1.29.0, 2.31.0].
    - Can only install one of: nesbot/carbon[1.29.1, 2.31.0].
    - Can only install one of: nesbot/carbon[1.29.2, 2.31.0].
    - Can only install one of: nesbot/carbon[1.30.0, 2.31.0].
    - Can only install one of: nesbot/carbon[1.31.0, 2.31.0].
    - Can only install one of: nesbot/carbon[1.31.1, 2.31.0].
    - Can only install one of: nesbot/carbon[1.32.0, 2.31.0].
    - Can only install one of: nesbot/carbon[1.33.0, 2.31.0].
    - Can only install one of: nesbot/carbon[1.34.0, 2.31.0].
    - Can only install one of: nesbot/carbon[1.34.1, 2.31.0].
    - Can only install one of: nesbot/carbon[1.34.2, 2.31.0].
    - Can only install one of: nesbot/carbon[1.34.3, 2.31.0].
    - Can only install one of: nesbot/carbon[1.34.4, 2.31.0].
    - Can only install one of: nesbot/carbon[1.35.0, 2.31.0].
    - Can only install one of: nesbot/carbon[1.35.1, 2.31.0].
    - Can only install one of: nesbot/carbon[1.36.0, 2.31.0].
    - Can only install one of: nesbot/carbon[1.36.1, 2.31.0].
    - Can only install one of: nesbot/carbon[1.36.2, 2.31.0].
    - Can only install one of: nesbot/carbon[1.37.0, 2.31.0].
    - Can only install one of: nesbot/carbon[1.37.1, 2.31.0].
    - Can only install one of: nesbot/carbon[1.38.0, 2.31.0].
    - Can only install one of: nesbot/carbon[1.38.1, 2.31.0].
    - Can only install one of: nesbot/carbon[1.38.2, 2.31.0].
    - Can only install one of: nesbot/carbon[1.38.3, 2.31.0].
    - Can only install one of: nesbot/carbon[1.38.4, 2.31.0].
    - Can only install one of: nesbot/carbon[1.39.0, 2.31.0].
    - Can only install one of: nesbot/carbon[1.39.1, 2.31.0].
    - Installation request for nesbot/carbon (locked at 2.31.0) -> satisfiable by nesbot/carbon[2.31.0].
`

Is it not available that can install this package with composer/carbon 2?

Thanks for your help!

**Comment by gerbenjacobs** [comment]
Fixed with #v4.0.0
