### ISSUE TITLE
check banned user?

### ISSUE THREAD

**Issue by fortniteFN** [gerbenjacobs/HabboAPI#58]
How is it possible to know if a user is banned or the profile does not exist?

https://github.com/gerbenjacobs/HabboAPI/issues/15

The last answer is still not clear to me, we need the Habbo ID to check it

And how would it be possible with the user?

that is, obtain if the user is banned or the profile does not exist

How can you get this?

user not exist: https://www.habbo.es/api/public/users?name=fqr34efg4er5
user ban : https://www.habbo.es/api/public/users?name=arturo

**Comment by gerbenjacobs** [comment]
You can't, that's the problem. There's no reliable way to check it.

In #15 we discuss a bunch of hacks to get this information. The bottomline is if you get "user-not-found" but their avatar stills returns `200 OK` then they're banned.
